### ISSUE TITLE
checkout geonetwork datadir fails

### ISSUE THREAD

**Issue by fvanderbiest** [georchestra/ansible#28]
TASK: [georchestra | checkout geonetwork datadir] ***************************** 
failed: [mygeorchestra] => {"cmd": "/usr/bin/git clone --origin origin --recursive --branch master https://github.com/georchestra/geonetwork_minimal_datadir /srv/data/geonetwork", "failed": true, "rc": 128}
stderr: fatal: destination path '/srv/data/geonetwork' already exists and is not an empty directory.

msg: fatal: destination path '/srv/data/geonetwork' already exists and is not an empty directory.

FATAL: all hosts have already failed -- aborting

**Comment by landryb** [comment]
Shouldnt happen unless something started tomcat-georchestra *before* the datadir checkout task is called... full log ?

**Comment by landryb** [comment]
And if /srv/data/geonetwork was already here, what was its content and the associated timestamps ?

**Comment by fvanderbiest** [comment]
Could not reproduce...

**Comment by fvanderbiest** [comment]
Funny, I can now reproduce on my computer at work, but not at home...

**Comment by fvanderbiest** [comment]
Log https://gist.github.com/fvanderbiest/81fb1b1f5cf6d49ff556 (at least the lines I could copy)

```
vagrant@debian-jessie:/srv/data/geonetwork$ ls -al
total 3692
drwxr-xr-x 5 tomcat8 tomcat8     4096 Feb 17 09:27 .
drwxr-xr-x 6 tomcat8 tomcat8     4096 Feb 17 09:23 ..
drwxr-xr-x 4 tomcat8 tomcat8     4096 Feb 17 09:27 config
drwxr-xr-x 7 tomcat8 tomcat8     4096 Feb 17 09:27 data
drwxr-xr-x 3 tomcat8 tomcat8     4096 Feb 17 09:27 index
-rw-r--r-- 1 tomcat8 tomcat8 10496000 Feb 17 09:29 wro4j-cache.h2.db
-rw-r--r-- 1 tomcat8 tomcat8      105 Feb 17 09:27 wro4j-cache.lock.db
```

**Comment by landryb** [comment]
So, geonetwork is started *before* the checkout task - okay, there's a race condition here. I need the tomcat instances to be force-started to unpack the webapps (done in roles/georchestra/tasks/wars.yml) and only later on the checkout is done (in roles/georchestra/tasks/geonetwork.yml).

I'll just have to think a bit about it, but maybe only reordering the subtasks in roles/georchestra/tasks/main.yml should fix it.

Otherwise, i can manually use the uncompress module to unzip wars, but that's "nicer" if tomcat does it imo.

**Comment by fvanderbiest** [comment]
> Otherwise, i can manually use the uncompress module to unzip wars, but that's "nicer" if tomcat does it imo.

yep
